# 🐼 DataFrame 탐색 — Student

예측 → 작성 → 실행 → 확인 순서로 강의 코드를 연습한다.

> **🖥️ 환경 설정**
>
> - **로컬**: 배포 폴더에서 `uv sync` 후 `uv run jupyter lab`
>
> - **Colab**: 고정 CSV 세 파일을 `data/` 폴더에 업로드한 뒤 실행
>
> **⌨️ 단축키 안내**
>
> | 단축키 | 동작 |
> |--------|------|
> | `Shift + Enter` | 셀 실행 후 다음 셀 이동 |
> | `Esc → A` | 위에 셀 삽입 |
> | `Esc → B` | 아래에 셀 삽입 |
> | `Esc → DD` | 셀 삭제 |


In [1]:
# 🖥️ 환경 설정
# - 로컬: 터미널에서 `uv sync` 실행 (pyproject.toml + uv.lock 동봉)
# - Colab: 고정 CSV를 data/ 폴더에 올린 뒤 !pip install pandas -q

import pandas as pd


In [2]:
# 🗂️ §300 shared_data 고정 CSV 읽기
df = pd.read_csv('data/kospi_listing.csv', dtype={'Code': str})
print(df.shape)
# 예상 출력:
# (40, 5)


(40, 5)


> **이 문법이 처음이면**
>
> 대괄호 하나는 Series, 대괄호 두 개는 DataFrame을 꺼낸다.
>
> 더 볼 사람을 위한 자습 자료는 다음 사이클에 추가됩니다.


> **이 문법이 처음이면**
>
> 라벨 `loc` 범위는 끝을 포함하고 위치 `iloc` 슬라이싱은 끝을 포함하지 않는다.
>
> 더 볼 사람을 위한 자습 자료는 다음 사이클에 추가됩니다.


## 300-1 — 컬럼 중심 데이터로 DataFrame 만들기

**문제**

`data_컬럼중심 = {'ticker': ['005930', '000660', '005935'], 'Marcap': [1464492791304000, 1178284184745000, 148839858156500]}` 딕셔너리를 만들고 `pd.DataFrame(data_컬럼중심)`으로 변환해 `df1`에 저장하세요.

**작성 위치**: 바로 아래 코드 셀에 위 문제의 코드를 입력하세요. instructor와 student는 같은 문제를 공유합니다.

[→ §2 강의노트](../notes/FD-02-300__dataframe.md)

In [3]:
# 📌 §300 cell_id=300:1 🔨 만들기 — 컬럼 중심과 행 중심
# 코드를 작성해주세요 👇
# 과제: 강의노트의 입력과 같은 결과가 나오도록 한 단계씩 작성한다.
# 힌트: 바로 위의 설명과 고정 CSV의 열 이름을 다시 확인한다.
data_컬럼중심 = {'ticker': ['005930', '000660', '005935'], 'Marcap': [1464492791304000, 1178284184745000, 148839858156500]}
df1=pd.DataFrame(data_컬럼중심)
# 예상 출력:
# 실행 후 강의노트의 결과와 비교하세요.


## 300-2 — 행 중심 데이터로 DataFrame 만들기

**문제**

`data_행중심 = [{'ticker': '005930', 'Marcap': 1464492791304000}, {'ticker': '000660', 'Marcap': 1178284184745000}, {'ticker': '005935', 'Marcap': 148839858156500}]` 리스트를 만들고 `pd.DataFrame(data_행중심)`으로 변환해 `df2`에 저장하세요. `df1`과 값·순서가 같은지 비교합니다.

**작성 위치**: 바로 아래 코드 셀에 위 문제의 코드를 입력하세요. instructor와 student는 같은 문제를 공유합니다.

[→ §2 강의노트](../notes/FD-02-300__dataframe.md)

In [ ]:
# 📌 §300 cell_id=300:2 🔨 만들기 — 컬럼 중심과 행 중심
# 코드를 작성해주세요 👇
# 과제: 강의노트의 입력과 같은 결과가 나오도록 한 단계씩 작성한다.
# 힌트: 바로 위의 설명과 고정 CSV의 열 이름을 다시 확인한다.

# 예상 출력:
# 실행 후 강의노트의 결과와 비교하세요.


## 300-3 — 표의 크기·컬럼·자료형·앞 3행 확인

**문제**

`data/kospi_listing.csv`를 `dtype={'Code': str}`로 읽어 `df`에 저장하세요. `df.shape`, `df.columns`, `df.dtypes`, `df.head(3)`을 이 순서로 출력하세요.

**작성 위치**: 바로 아래 코드 셀에 위 문제의 코드를 입력하세요. instructor와 student는 같은 문제를 공유합니다.

[→ §3 강의노트](../notes/FD-02-300__dataframe.md)

In [1]:
# 📌 §300 cell_id=300:3 🔍 표를 받으면 가장 먼저 하는 세 가지
# 코드를 작성해주세요 👇
# 과제: 강의노트의 입력과 같은 결과가 나오도록 한 단계씩 작성한다.
# 힌트: 바로 위의 설명과 고정 CSV의 열 이름을 다시 확인한다.
import pandas as pd
df=pd.read_csv("data/kospi_listing.csv", dtype={'Code':str})
df.shape
df.columns
df.dtypes
df.head(3)
# 예상 출력:
# 실행 후 강의노트의 결과와 비교하세요.


,Code,Name,Market,Sector,Marcap
0,005930,삼성전자,KOSPI,전기전자,1464492791304000
1,000660,SK하이닉스,KOSPI,전기전자,1178284184745000
2,005935,삼성전자우,KOSPI,전기전자,148839858156500


## 300-4 — Series와 DataFrame 선택 결과 비교

**문제**

`type(df['Marcap'])`와 `type(df[['Name', 'Marcap']])`을 각각 출력해 대괄호 1개(Series)와 2개(DataFrame)의 결과 타입을 비교합니다.

**작성 위치**: 바로 아래 코드 셀에 위 문제의 코드를 입력하세요. instructor와 student는 같은 문제를 공유합니다.

[→ §4 강의노트](../notes/FD-02-300__dataframe.md)

In [6]:
# 📌 §300 cell_id=300:4 🎯 컬럼을 꺼내면 Series가 된다
# 코드를 작성해주세요 👇
# 과제: 강의노트의 입력과 같은 결과가 나오도록 한 단계씩 작성한다.
# 힌트: 바로 위의 설명과 고정 CSV의 열 이름을 다시 확인한다.
print(type(df[['Name']]))
# 예상 출력:
# 실행 후 강의노트의 결과와 비교하세요.


<class 'pandas.DataFrame'>


## 300-5 — Marcap 평균 계산

**문제**

시가총액(`Marcap`) 컬럼의 평균을 계산합니다.

**작성 위치**: 바로 아래 코드 셀에 위 문제의 코드를 입력하세요. instructor와 student는 같은 문제를 공유합니다.

[→ §4 강의노트](../notes/FD-02-300__dataframe.md)

In [ ]:
# 📌 §300 cell_id=300:5 🎯 컬럼을 꺼내면 Series가 된다
# 코드를 작성해주세요 👇
# 과제: 강의노트의 입력과 같은 결과가 나오도록 한 단계씩 작성한다.
# 힌트: 바로 위의 설명과 고정 CSV의 열 이름을 다시 확인한다.
print(df['Marcap'].mean())
# 예상 출력:
# 실행 후 강의노트의 결과와 비교하세요.


108527194534476.25


## 400-1 — Code를 인덱스로 설정하고 loc·iloc 비교

**문제**

`df.set_index('Code')`로 `df_indexed`를 만드세요. `df_indexed.loc['005930', 'Name']`와 `df_indexed.iloc[0]['Name']`을 출력해 둘 다 삼성전자인지 확인합니다.

**작성 위치**: 바로 아래 코드 셀에 위 문제의 코드를 입력하세요. instructor와 student는 같은 문제를 공유합니다.

[→ §1 강의노트](../notes/FD-02-400__indexing-filter.md)

In [10]:
# 📌 §400 cell_id=400:1 실습
# 코드를 작성해주세요 👇
# 과제: 강의노트의 입력과 같은 결과가 나오도록 한 단계씩 작성한다.
# 힌트: 바로 위의 설명과 고정 CSV의 열 이름을 다시 확인한다.
df_indexed = df.set_index('Code')

print(df_indexed.loc['005930'][ 'Name'])   # 이름으로: '005930' 행
print(df_indexed.iloc[0]['Name'])         # 번호로: 0번째 행
# 예상 출력:
# 실행 후 강의노트의 결과와 비교하세요.


삼성전자
삼성전자


## 400-2 — 새 행 추가 후 loc·iloc 결과 비교

**문제**

`{"Name": "신규상장A", "Market": "KOSPI", "Sector": "IT서비스", "Marcap": 5_000_000_000_000}`을 인덱스 `"999999"`로 하는 한 행짜리 DataFrame을 만들어 `pd.concat`으로 `df_indexed` 맨 앞에 붙이고 `df_indexed2`에 저장하세요. `df_indexed2.loc['005930', 'Name']`와 `df_indexed2.iloc[0]['Name']`을 출력하세요.

**작성 위치**: 바로 아래 코드 셀에 위 문제의 코드를 입력하세요. instructor와 student는 같은 문제를 공유합니다.

[→ §1 강의노트](../notes/FD-02-400__indexing-filter.md)

In [12]:
# 📌 §400 cell_id=400:2 실습
# 코드를 작성해주세요 👇
# 과제: 강의노트의 입력과 같은 결과가 나오도록 한 단계씩 작성한다.
new_df=pd.DataFrame(
    [{"Name": "신규상장A", "Market": "KOSPI", "Sector": "IT서비스", "Marcap": 5_000_000_000_000}]
    ,index=["999999"])
df_indexed2=pd.concat([new_df,df_indexed])

print(df_indexed2.loc['005930':'005935','Name'])
print(df_indexed2.iloc[0]['Name'])
# 예상 출력:
# 실행 후 강의노트의 결과와 비교하세요.


005930      삼성전자
000660    SK하이닉스
005935     삼성전자우
Name: Name, dtype: str
신규상장A


## 400-3 — loc·iloc 슬라이싱 범위 비교

**문제**

`df_indexed.loc['005930':'005935'][['Name']]`와 `df_indexed.iloc[0:2][['Name']]`을 각각 출력해 `loc`(끝 포함, 3행)와 `iloc`(끝 미포함, 2행)의 행 개수 차이를 비교합니다.

**작성 위치**: 바로 아래 코드 셀에 위 문제의 코드를 입력하세요. instructor와 student는 같은 문제를 공유합니다.

[→ §2 강의노트](../notes/FD-02-400__indexing-filter.md)

In [ ]:
# 📌 §400 cell_id=400:3 실습
# 코드를 작성해주세요 👇
# 과제: 강의노트의 입력과 같은 결과가 나오도록 한 단계씩 작성한다.
# 힌트: 바로 위의 설명과 고정 CSV의 열 이름을 다시 확인한다.

# 예상 출력:
# 실행 후 강의노트의 결과와 비교하세요.
